require "qmmr.options"
require "qmmr.keymaps"
require "qmmr.plugins"
require "qmmr.colorscheme"
require "qmmr.cmp"
require "qmmr.lsp"
require "qmmr.telescope"
require "qmmr.treesitter"
require "qmmr.nvim-tree"
require "qmmr.null-ls"
require "qmmr.prettier"
require "qmmr.bufferline"

